### ISSUE TITLE
.STL files are saving as 0 bytes

### ISSUE THREAD

**Issue by Dylan-Kazak** [ThatcherC/Terrain2STL#16]
Hello, I recently discovered this website, Terrain2STL from the youtube channel Make Anything.
He used it to create his own 3d puzzles, though i do not own a 3d printer I
 wanted to see what it was like so save some terrain and view it in 3d builder. but when i used it, Multiple times, all the files were being saved as 0 bytes and wold not open in any program. I even tried in moon2stl and got the same problem.
Could anyone explain why this is happening
Here is one:
[terrain-0 (7).zip](https://github.com/ThatcherC/Terrain2STL/files/2724785/terrain-0.7.zip)

**Comment by ThatcherC** [comment]
Should be resolved now - the server's disk was full so no new files could be produced. Usually a cron job on the server takes care of cleaning out old STLs, but I moved the server recently and forgot to set that up again. I replicated the error you were having and after clearing the disk the site works again! Thank you for reporting this issue!

**Comment by mcbailey** [comment]
@ThatcherC Still seeing this... Fill up again?

**Comment by Dylan-Kazak** [comment]
Yeah its still not working for me either

**Comment by Dylan-Kazak** [comment]
The server is probably full again

**Comment by Dylan-Kazak** [comment]
> Should be resolved now - the server's disk was full so no new files could be produced. Usually a cron job on the server takes care of cleaning out old STLs, but I moved the server recently and forgot to set that up again. I replicated the error you were having and after clearing the disk the site works again! Thank you for reporting this issue!

Thanks. I understand the problem now.

**Comment by Dylan-Kazak** [comment]
Now Terrain2STL is not saving anything at all, it just says 404 not found when I press download, But moon2stl still just saves as 0 bytes.

**Comment by mcbailey** [comment]
Yes, to be clear I see the 404 problem on terrain as well.

**Comment by mcbailey** [comment]
To be clear, I see the 404 issue as well.

**Comment by ThatcherC** [comment]
Hi all, problem should be resolved now. @Dylan-Kazak was right - the server filled up again, which meant the server program crashed for the 10th time, so it wasn't automatically restarted. That's what caused the 404. STLs are now deleted every hour so it'll take a lot of traffic to crash the server again :D

**Comment by Dylan-Kazak** [comment]
Yes thanks, Its Working fine now. Just one question, How big of a box can you do without messing everything up?

**Comment by Dylan-Kazak** [comment]
Oh Well I can Make A File the size of 90MB without anything crashing, That's good

**Comment by dwhacks** [comment]
Getting 404 Not Found on the download now! Excited to try this!
