### ISSUE TITLE
Flat surface in Norway

### ISSUE THREAD

**Issue by mattiz** [ThatcherC/Terrain2STL#7]
Thank you for a great program!

I seem to have stumbled upon a problem. When selecting some places in Norway, I get partial or no height curves. Please take a look at the attached images for an example.

![terrain2stl_cura](https://cloud.githubusercontent.com/assets/72491/8655369/fb7a30ea-2990-11e5-84b2-3847fd9d99a1.jpg)
![terrain2stl_map](https://cloud.githubusercontent.com/assets/72491/8655371/fb7b9d7c-2990-11e5-8019-8e8bc46bcae1.jpg)

**Comment by ThatcherC** [comment]
Unfortunately, the elevation data I use only goes up to 66 degrees north latitude. I think a lot of Norway is above 66 degrees north, so you won't get good models. There's not anything I can do about it except find a new data source...

Would it be helpful to add a visual indication of where the dataset ends?
